name: kasata
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  location: ^1.4.1
  flutter_map:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  camera:
  firebase_storage: "^0.3.5"
  firebase_auth:
  google_sign_in:
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/teaserAsset1.png
   - images/teaserAsset2.png
   - images/teaserAsset3.png
   - images/teaserAsset4.png
   - images/loginAsset.png
   - images/annuaireAsset1.png
   - images/annuaireAsset2.png
   - images/annuaireAsset3.png
   - images/annuaireAsset4.png
   - images/emptyAsset.png
   - images/alerteAsset.png
   - images/infoAsset1.jpg
   - images/infoAsset2.jpg
   - images/infoAsset3.jpg
   - images/infoAsset4.jpg
   - images/securiteAsset.png
   - images/deteriorationAsset.png
   - images/logo_kassata.png
   - images/logo_kassata1.png
   - images/google.png
   - images/account.png
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LiberationSerif
      fonts:
        - asset: fonts/LiberationSerif-Regular.ttf
    - family: bebas
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf